spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    # url: jdbc:mysql://192.168.0.4/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.4
    port: 6379
server:
  context-path: /sell
  port: 9999



    # 默认 info  可以指定到某个类
    #logging:
    #  pattern:
    #    console: "%d - %msg%n"   # 日期--信息--换行
    #    level: debug
  #    file: E:\workspace\WeChatPay\log\sell.log

  #    com.imooc.LoggerTest: debug

  #wechat:
  #mpAppId: wxd898fcb01713c658
  #mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  #openAppId: wx6ad144e54af67d87
  #openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  #mchId: 1483469312
  #mchKey: 06C56A89949D617xxxxxxxxxxx
  #keyPath: /var/weixin_cert/h5.p12
  #notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  #templateId:
  #orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

  #projectUrl:
  #wechatMpAuthorize: http://sell.natapp4.cc
  #wechatOpenAuthorize: http://sell.natapp4.cc
  #sell: http://sell.natapp4.cc
